# Generated by Django 4.1.2 on 2022-10-16 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_weather_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='MowscowWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-70), django.core.validators.MaxValueValidator(50)])),
            ],
            options={
                'verbose_name': 'Погода',
                'verbose_name_plural': 'Погода',
            },
        ),
        migrations.RemoveField(
            model_name='weather',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
