# Generated by Django 4.1.2 on 2022-10-16 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_mowscowweather_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mowscowweather',
            name='temperature',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-70), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
